# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Hakeem/Desktop/Basys3_Projects/RISCV_DualCore/RISCV_DualCore.srcs/sources_1/bd/dualBlaze/ip/dualBlaze_mdm_1_0/dualBlaze_mdm_1_0.xci
# IP: The module: 'dualBlaze_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Hakeem/Desktop/Basys3_Projects/RISCV_DualCore/RISCV_DualCore.gen/sources_1/bd/dualBlaze/ip/dualBlaze_mdm_1_0/dualBlaze_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualBlaze_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Hakeem/Desktop/Basys3_Projects/RISCV_DualCore/RISCV_DualCore.gen/sources_1/bd/dualBlaze/ip/dualBlaze_mdm_1_0/dualBlaze_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualBlaze_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Hakeem/Desktop/Basys3_Projects/RISCV_DualCore/RISCV_DualCore.srcs/sources_1/bd/dualBlaze/ip/dualBlaze_mdm_1_0/dualBlaze_mdm_1_0.xci
# IP: The module: 'dualBlaze_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Hakeem/Desktop/Basys3_Projects/RISCV_DualCore/RISCV_DualCore.gen/sources_1/bd/dualBlaze/ip/dualBlaze_mdm_1_0/dualBlaze_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualBlaze_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Hakeem/Desktop/Basys3_Projects/RISCV_DualCore/RISCV_DualCore.gen/sources_1/bd/dualBlaze/ip/dualBlaze_mdm_1_0/dualBlaze_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'dualBlaze_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
