# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Hakeem/Desktop/Basys3_Projects/OLED/OLED.srcs/sources_1/bd/OLED_IP/ip/OLED_IP_dlmb_bram_if_cntlr_1/OLED_IP_dlmb_bram_if_cntlr_1.xci
# IP: The module: 'OLED_IP_dlmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Hakeem/Desktop/Basys3_Projects/OLED/OLED.gen/sources_1/bd/OLED_IP/ip/OLED_IP_dlmb_bram_if_cntlr_1/OLED_IP_dlmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLED_IP_dlmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Hakeem/Desktop/Basys3_Projects/OLED/OLED.srcs/sources_1/bd/OLED_IP/ip/OLED_IP_dlmb_bram_if_cntlr_1/OLED_IP_dlmb_bram_if_cntlr_1.xci
# IP: The module: 'OLED_IP_dlmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Hakeem/Desktop/Basys3_Projects/OLED/OLED.gen/sources_1/bd/OLED_IP/ip/OLED_IP_dlmb_bram_if_cntlr_1/OLED_IP_dlmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLED_IP_dlmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
